spring.application.name=Notification-service


server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.kafka.bootstrap-servers=kafka-3a7630e2-jakartaeeproject.e.aivencloud.com:11299

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=<username> password=<password>


spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest