spring.application.name=api-gateway1




server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=false

jwt.secret={jwt-secret}